// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTypesHandlerFunc turns a function with the right signature into a get types handler
type GetTypesHandlerFunc func(GetTypesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTypesHandlerFunc) Handle(params GetTypesParams) middleware.Responder {
	return fn(params)
}

// GetTypesHandler interface for that can handle valid get types params
type GetTypesHandler interface {
	Handle(GetTypesParams) middleware.Responder
}

// NewGetTypes creates a new http.Handler for the get types operation
func NewGetTypes(ctx *middleware.Context, handler GetTypesHandler) *GetTypes {
	return &GetTypes{Context: ctx, Handler: handler}
}

/*
	GetTypes swagger:route GET /types types getTypes

Serves the different types cards can be. Fx "Minion" or "Spell"
*/
type GetTypes struct {
	Context *middleware.Context
	Handler GetTypesHandler
}

func (o *GetTypes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTypesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
