// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetV1TypesOKCode is the HTTP code returned for type GetV1TypesOK
const GetV1TypesOKCode int = 200

/*
GetV1TypesOK Returns all types

swagger:response getV1TypesOK
*/
type GetV1TypesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Types `json:"body,omitempty"`
}

// NewGetV1TypesOK creates GetV1TypesOK with default headers values
func NewGetV1TypesOK() *GetV1TypesOK {

	return &GetV1TypesOK{}
}

// WithPayload adds the payload to the get v1 types o k response
func (o *GetV1TypesOK) WithPayload(payload []*models.Types) *GetV1TypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 types o k response
func (o *GetV1TypesOK) SetPayload(payload []*models.Types) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1TypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Types, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1TypesInternalServerErrorCode is the HTTP code returned for type GetV1TypesInternalServerError
const GetV1TypesInternalServerErrorCode int = 500

/*
GetV1TypesInternalServerError Something went wrong internally

swagger:response getV1TypesInternalServerError
*/
type GetV1TypesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1TypesInternalServerError creates GetV1TypesInternalServerError with default headers values
func NewGetV1TypesInternalServerError() *GetV1TypesInternalServerError {

	return &GetV1TypesInternalServerError{}
}

// WithPayload adds the payload to the get v1 types internal server error response
func (o *GetV1TypesInternalServerError) WithPayload(payload *models.Error) *GetV1TypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 types internal server error response
func (o *GetV1TypesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1TypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
