// Code generated by go-swagger; DO NOT EDIT.

package classes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetV1ClassesOKCode is the HTTP code returned for type GetV1ClassesOK
const GetV1ClassesOKCode int = 200

/*
GetV1ClassesOK Returns all classes

swagger:response getV1ClassesOK
*/
type GetV1ClassesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Classes `json:"body,omitempty"`
}

// NewGetV1ClassesOK creates GetV1ClassesOK with default headers values
func NewGetV1ClassesOK() *GetV1ClassesOK {

	return &GetV1ClassesOK{}
}

// WithPayload adds the payload to the get v1 classes o k response
func (o *GetV1ClassesOK) WithPayload(payload []*models.Classes) *GetV1ClassesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 classes o k response
func (o *GetV1ClassesOK) SetPayload(payload []*models.Classes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1ClassesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Classes, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1ClassesInternalServerErrorCode is the HTTP code returned for type GetV1ClassesInternalServerError
const GetV1ClassesInternalServerErrorCode int = 500

/*
GetV1ClassesInternalServerError Something went wrong internally

swagger:response getV1ClassesInternalServerError
*/
type GetV1ClassesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1ClassesInternalServerError creates GetV1ClassesInternalServerError with default headers values
func NewGetV1ClassesInternalServerError() *GetV1ClassesInternalServerError {

	return &GetV1ClassesInternalServerError{}
}

// WithPayload adds the payload to the get v1 classes internal server error response
func (o *GetV1ClassesInternalServerError) WithPayload(payload *models.Error) *GetV1ClassesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 classes internal server error response
func (o *GetV1ClassesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1ClassesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
