[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz"
nixPkgs = ["go_1_26"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -o out ./cmd"]

[start]
cmd = "./out"

[variables]
GOTOOLCHAIN = "local"
