// Code generated by go-swagger; DO NOT EDIT.

package update

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdateOKCode is the HTTP code returned for type PostUpdateOK
const PostUpdateOKCode int = 200

/*
PostUpdateOK OK

swagger:response postUpdateOK
*/
type PostUpdateOK struct {
}

// NewPostUpdateOK creates PostUpdateOK with default headers values
func NewPostUpdateOK() *PostUpdateOK {

	return &PostUpdateOK{}
}

// WriteResponse to the client
func (o *PostUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostUpdateUnauthorizedCode is the HTTP code returned for type PostUpdateUnauthorized
const PostUpdateUnauthorizedCode int = 401

/*
PostUpdateUnauthorized Unauthorized request

swagger:response postUpdateUnauthorized
*/
type PostUpdateUnauthorized struct {
}

// NewPostUpdateUnauthorized creates PostUpdateUnauthorized with default headers values
func NewPostUpdateUnauthorized() *PostUpdateUnauthorized {

	return &PostUpdateUnauthorized{}
}

// WriteResponse to the client
func (o *PostUpdateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
