// Code generated by go-swagger; DO NOT EDIT.

package update

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUpdateAcceptedCode is the HTTP code returned for type PostUpdateAccepted
const PostUpdateAcceptedCode int = 202

/*
PostUpdateAccepted Update started

swagger:response postUpdateAccepted
*/
type PostUpdateAccepted struct {
}

// NewPostUpdateAccepted creates PostUpdateAccepted with default headers values
func NewPostUpdateAccepted() *PostUpdateAccepted {

	return &PostUpdateAccepted{}
}

// WriteResponse to the client
func (o *PostUpdateAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

// PostUpdateUnauthorizedCode is the HTTP code returned for type PostUpdateUnauthorized
const PostUpdateUnauthorizedCode int = 401

/*
PostUpdateUnauthorized Unauthorized request

swagger:response postUpdateUnauthorized
*/
type PostUpdateUnauthorized struct {
}

// NewPostUpdateUnauthorized creates PostUpdateUnauthorized with default headers values
func NewPostUpdateUnauthorized() *PostUpdateUnauthorized {

	return &PostUpdateUnauthorized{}
}

// WriteResponse to the client
func (o *PostUpdateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
