// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetCardsOKCode is the HTTP code returned for type GetCardsOK
const GetCardsOKCode int = 200

/*
GetCardsOK Returns the cards based on query. If there is no query, cards will be returned based on their manaCost in ascending order.

swagger:response getCardsOK
*/
type GetCardsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cards `json:"body,omitempty"`
}

// NewGetCardsOK creates GetCardsOK with default headers values
func NewGetCardsOK() *GetCardsOK {

	return &GetCardsOK{}
}

// WithPayload adds the payload to the get cards o k response
func (o *GetCardsOK) WithPayload(payload *models.Cards) *GetCardsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cards o k response
func (o *GetCardsOK) SetPayload(payload *models.Cards) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCardsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCardsBadRequestCode is the HTTP code returned for type GetCardsBadRequest
const GetCardsBadRequestCode int = 400

/*
GetCardsBadRequest The query is incorrect

swagger:response getCardsBadRequest
*/
type GetCardsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCardsBadRequest creates GetCardsBadRequest with default headers values
func NewGetCardsBadRequest() *GetCardsBadRequest {

	return &GetCardsBadRequest{}
}

// WithPayload adds the payload to the get cards bad request response
func (o *GetCardsBadRequest) WithPayload(payload *models.Error) *GetCardsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cards bad request response
func (o *GetCardsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCardsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCardsInternalServerErrorCode is the HTTP code returned for type GetCardsInternalServerError
const GetCardsInternalServerErrorCode int = 500

/*
GetCardsInternalServerError Something went wrong internally

swagger:response getCardsInternalServerError
*/
type GetCardsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCardsInternalServerError creates GetCardsInternalServerError with default headers values
func NewGetCardsInternalServerError() *GetCardsInternalServerError {

	return &GetCardsInternalServerError{}
}

// WithPayload adds the payload to the get cards internal server error response
func (o *GetCardsInternalServerError) WithPayload(payload *models.Error) *GetCardsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cards internal server error response
func (o *GetCardsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCardsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
