// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRichCardsHandlerFunc turns a function with the right signature into a get rich cards handler
type GetRichCardsHandlerFunc func(GetRichCardsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRichCardsHandlerFunc) Handle(params GetRichCardsParams) middleware.Responder {
	return fn(params)
}

// GetRichCardsHandler interface for that can handle valid get rich cards params
type GetRichCardsHandler interface {
	Handle(GetRichCardsParams) middleware.Responder
}

// NewGetRichCards creates a new http.Handler for the get rich cards operation
func NewGetRichCards(ctx *middleware.Context, handler GetRichCardsHandler) *GetRichCards {
	return &GetRichCards{Context: ctx, Handler: handler}
}

/*
	GetRichCards swagger:route GET /richcards cards getRichCards

Rich cards contain names instead of IDs for e.g. CardType and CardSet.
*/
type GetRichCards struct {
	Context *middleware.Context
	Handler GetRichCardsHandler
}

func (o *GetRichCards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRichCardsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
