// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetV1CardsOKCode is the HTTP code returned for type GetV1CardsOK
const GetV1CardsOKCode int = 200

/*
GetV1CardsOK Returns the cards based on query. If there is no query, cards will be returned based on their manaCost in ascending order.

swagger:response getV1CardsOK
*/
type GetV1CardsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cards `json:"body,omitempty"`
}

// NewGetV1CardsOK creates GetV1CardsOK with default headers values
func NewGetV1CardsOK() *GetV1CardsOK {

	return &GetV1CardsOK{}
}

// WithPayload adds the payload to the get v1 cards o k response
func (o *GetV1CardsOK) WithPayload(payload *models.Cards) *GetV1CardsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 cards o k response
func (o *GetV1CardsOK) SetPayload(payload *models.Cards) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1CardsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetV1CardsInternalServerErrorCode is the HTTP code returned for type GetV1CardsInternalServerError
const GetV1CardsInternalServerErrorCode int = 500

/*
GetV1CardsInternalServerError Something went wrong internally

swagger:response getV1CardsInternalServerError
*/
type GetV1CardsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1CardsInternalServerError creates GetV1CardsInternalServerError with default headers values
func NewGetV1CardsInternalServerError() *GetV1CardsInternalServerError {

	return &GetV1CardsInternalServerError{}
}

// WithPayload adds the payload to the get v1 cards internal server error response
func (o *GetV1CardsInternalServerError) WithPayload(payload *models.Error) *GetV1CardsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 cards internal server error response
func (o *GetV1CardsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1CardsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
