// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetRichCardsOKCode is the HTTP code returned for type GetRichCardsOK
const GetRichCardsOKCode int = 200

/*
GetRichCardsOK Returns rich cards by query. If there is no query, cards are returned by manaCost ascending.

swagger:response getRichCardsOK
*/
type GetRichCardsOK struct {

	/*
	  In: Body
	*/
	Payload *models.RichCards `json:"body,omitempty"`
}

// NewGetRichCardsOK creates GetRichCardsOK with default headers values
func NewGetRichCardsOK() *GetRichCardsOK {

	return &GetRichCardsOK{}
}

// WithPayload adds the payload to the get rich cards o k response
func (o *GetRichCardsOK) WithPayload(payload *models.RichCards) *GetRichCardsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rich cards o k response
func (o *GetRichCardsOK) SetPayload(payload *models.RichCards) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRichCardsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRichCardsInternalServerErrorCode is the HTTP code returned for type GetRichCardsInternalServerError
const GetRichCardsInternalServerErrorCode int = 500

/*
GetRichCardsInternalServerError Something went wrong internally

swagger:response getRichCardsInternalServerError
*/
type GetRichCardsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRichCardsInternalServerError creates GetRichCardsInternalServerError with default headers values
func NewGetRichCardsInternalServerError() *GetRichCardsInternalServerError {

	return &GetRichCardsInternalServerError{}
}

// WithPayload adds the payload to the get rich cards internal server error response
func (o *GetRichCardsInternalServerError) WithPayload(payload *models.Error) *GetRichCardsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rich cards internal server error response
func (o *GetRichCardsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRichCardsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
