// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetV1RichcardsOKCode is the HTTP code returned for type GetV1RichcardsOK
const GetV1RichcardsOKCode int = 200

/*
GetV1RichcardsOK Returns the cards based on query. If there is no query, cards will be returned based on their manaCost in ascending order.

swagger:response getV1RichcardsOK
*/
type GetV1RichcardsOK struct {

	/*
	  In: Body
	*/
	Payload *models.RichCards `json:"body,omitempty"`
}

// NewGetV1RichcardsOK creates GetV1RichcardsOK with default headers values
func NewGetV1RichcardsOK() *GetV1RichcardsOK {

	return &GetV1RichcardsOK{}
}

// WithPayload adds the payload to the get v1 richcards o k response
func (o *GetV1RichcardsOK) WithPayload(payload *models.RichCards) *GetV1RichcardsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 richcards o k response
func (o *GetV1RichcardsOK) SetPayload(payload *models.RichCards) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1RichcardsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetV1RichcardsInternalServerErrorCode is the HTTP code returned for type GetV1RichcardsInternalServerError
const GetV1RichcardsInternalServerErrorCode int = 500

/*
GetV1RichcardsInternalServerError Something went wrong internally

swagger:response getV1RichcardsInternalServerError
*/
type GetV1RichcardsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1RichcardsInternalServerError creates GetV1RichcardsInternalServerError with default headers values
func NewGetV1RichcardsInternalServerError() *GetV1RichcardsInternalServerError {

	return &GetV1RichcardsInternalServerError{}
}

// WithPayload adds the payload to the get v1 richcards internal server error response
func (o *GetV1RichcardsInternalServerError) WithPayload(payload *models.Error) *GetV1RichcardsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 richcards internal server error response
func (o *GetV1RichcardsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1RichcardsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
