// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostCardsUpdateHandlerFunc turns a function with the right signature into a post cards update handler
type PostCardsUpdateHandlerFunc func(PostCardsUpdateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCardsUpdateHandlerFunc) Handle(params PostCardsUpdateParams) middleware.Responder {
	return fn(params)
}

// PostCardsUpdateHandler interface for that can handle valid post cards update params
type PostCardsUpdateHandler interface {
	Handle(PostCardsUpdateParams) middleware.Responder
}

// NewPostCardsUpdate creates a new http.Handler for the post cards update operation
func NewPostCardsUpdate(ctx *middleware.Context, handler PostCardsUpdateHandler) *PostCardsUpdate {
	return &PostCardsUpdate{Context: ctx, Handler: handler}
}

/*
	PostCardsUpdate swagger:route POST /cards/update cards postCardsUpdate

Checks for updates to cards
*/
type PostCardsUpdate struct {
	Context *middleware.Context
	Handler PostCardsUpdateHandler
}

func (o *PostCardsUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCardsUpdateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
