// Code generated by go-swagger; DO NOT EDIT.

package cards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// PostCardsUpdateOKCode is the HTTP code returned for type PostCardsUpdateOK
const PostCardsUpdateOKCode int = 200

/*
PostCardsUpdateOK OK

swagger:response postCardsUpdateOK
*/
type PostCardsUpdateOK struct {
}

// NewPostCardsUpdateOK creates PostCardsUpdateOK with default headers values
func NewPostCardsUpdateOK() *PostCardsUpdateOK {

	return &PostCardsUpdateOK{}
}

// WriteResponse to the client
func (o *PostCardsUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostCardsUpdateUnauthorizedCode is the HTTP code returned for type PostCardsUpdateUnauthorized
const PostCardsUpdateUnauthorizedCode int = 401

/*
PostCardsUpdateUnauthorized Unauthorized request

swagger:response postCardsUpdateUnauthorized
*/
type PostCardsUpdateUnauthorized struct {
}

// NewPostCardsUpdateUnauthorized creates PostCardsUpdateUnauthorized with default headers values
func NewPostCardsUpdateUnauthorized() *PostCardsUpdateUnauthorized {

	return &PostCardsUpdateUnauthorized{}
}

// WriteResponse to the client
func (o *PostCardsUpdateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostCardsUpdateInternalServerErrorCode is the HTTP code returned for type PostCardsUpdateInternalServerError
const PostCardsUpdateInternalServerErrorCode int = 500

/*
PostCardsUpdateInternalServerError Something went wrong internally

swagger:response postCardsUpdateInternalServerError
*/
type PostCardsUpdateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCardsUpdateInternalServerError creates PostCardsUpdateInternalServerError with default headers values
func NewPostCardsUpdateInternalServerError() *PostCardsUpdateInternalServerError {

	return &PostCardsUpdateInternalServerError{}
}

// WithPayload adds the payload to the post cards update internal server error response
func (o *PostCardsUpdateInternalServerError) WithPayload(payload *models.Error) *PostCardsUpdateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post cards update internal server error response
func (o *PostCardsUpdateInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCardsUpdateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
