// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Duals duals
//
// swagger:model duals
type Duals struct {

	// constructed
	Constructed bool `json:"constructed,omitempty"`

	// relevant
	Relevant bool `json:"relevant,omitempty"`
}

// Validate validates this duals
func (m *Duals) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this duals based on context it is used
func (m *Duals) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Duals) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Duals) UnmarshalBinary(b []byte) error {
	var res Duals
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
