// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Info info
//
// swagger:model info
type Info struct {

	// amount of cards
	AmountOfCards int64 `json:"amountOfCards,omitempty"`

	// Seconds since last update
	TimeSinceLastUpdate int64 `json:"timeSinceLastUpdate,omitempty"`

	// Uptime in hours
	Uptime int64 `json:"uptime,omitempty"`
}

// Validate validates this info
func (m *Info) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this info based on context it is used
func (m *Info) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Info) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Info) UnmarshalBinary(b []byte) error {
	var res Info
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
