// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Keywords keywords
//
// swagger:model keywords
type Keywords struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this keywords
func (m *Keywords) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this keywords based on context it is used
func (m *Keywords) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Keywords) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Keywords) UnmarshalBinary(b []byte) error {
	var res Keywords
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
