// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Rarities rarities
//
// swagger:model rarities
type Rarities struct {

	// craftingcost
	Craftingcost []int64 `json:"craftingcost"`

	// dustvalue
	Dustvalue []int64 `json:"dustvalue"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this rarities
func (m *Rarities) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rarities based on context it is used
func (m *Rarities) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Rarities) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Rarities) UnmarshalBinary(b []byte) error {
	var res Rarities
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
