// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Hearthstone Card Service API
//
//	Serves Hearthstone cards
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 1.0.0
//	Contact: William Winkler<williambwinkler@gmail.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
