// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Serves Hearthstone cards",
    "title": "Hearthstone Card Service API",
    "contact": {
      "name": "William Winkler",
      "email": "williambwinkler@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/cards": {
      "get": {
        "description": "Returns cards as they are stored",
        "tags": [
          "cards"
        ],
        "operationId": "getCards",
        "parameters": [
          {
            "$ref": "#/parameters/cardNameParam"
          },
          {
            "$ref": "#/parameters/manaCostParam"
          },
          {
            "$ref": "#/parameters/healthParam"
          },
          {
            "$ref": "#/parameters/attackParam"
          },
          {
            "$ref": "#/parameters/classParam"
          },
          {
            "$ref": "#/parameters/rarityParam"
          },
          {
            "$ref": "#/parameters/typeParam"
          },
          {
            "$ref": "#/parameters/keywordsParam"
          },
          {
            "$ref": "#/parameters/setParam"
          },
          {
            "$ref": "#/parameters/pageParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns cards by query. If there is no query, cards are returned by manaCost ascending.",
            "schema": {
              "$ref": "#/definitions/cards"
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/classes": {
      "get": {
        "description": "Serves card classes, e.g. Warlock or Neutral.",
        "tags": [
          "classes"
        ],
        "operationId": "getClasses",
        "responses": {
          "200": {
            "description": "Returns all classes",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/classes"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/keywords": {
      "get": {
        "description": "Serves card keywords, e.g. Taunt or Quest.",
        "tags": [
          "keywords"
        ],
        "operationId": "getKeywords",
        "responses": {
          "200": {
            "description": "Returns all keywords",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/keywords"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/rarities": {
      "get": {
        "description": "Serves card rarities, e.g. Common or Legendary.",
        "tags": [
          "rarities"
        ],
        "operationId": "getRarities",
        "responses": {
          "200": {
            "description": "Returns all rarities",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/rarities"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/richcards": {
      "get": {
        "description": "Rich cards contain names instead of IDs for e.g. CardType and CardSet.",
        "tags": [
          "cards"
        ],
        "operationId": "getRichCards",
        "parameters": [
          {
            "$ref": "#/parameters/cardNameParam"
          },
          {
            "$ref": "#/parameters/manaCostParam"
          },
          {
            "$ref": "#/parameters/healthParam"
          },
          {
            "$ref": "#/parameters/attackParam"
          },
          {
            "$ref": "#/parameters/classParam"
          },
          {
            "$ref": "#/parameters/rarityParam"
          },
          {
            "$ref": "#/parameters/typeParam"
          },
          {
            "$ref": "#/parameters/keywordsParam"
          },
          {
            "$ref": "#/parameters/setParam"
          },
          {
            "$ref": "#/parameters/pageParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns rich cards by query. If there is no query, cards are returned by manaCost ascending.",
            "schema": {
              "$ref": "#/definitions/richCards"
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/sets": {
      "get": {
        "description": "Cards can belong to different sets or expansions. Returns all sets.",
        "tags": [
          "sets"
        ],
        "operationId": "getSets",
        "responses": {
          "200": {
            "description": "Returns all sets",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/sets"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/types": {
      "get": {
        "description": "Serves card types, e.g. Minion or Spell.",
        "tags": [
          "types"
        ],
        "operationId": "getTypes",
        "responses": {
          "200": {
            "description": "Returns all types",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/types"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/update": {
      "post": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Checks for updates to Hearthstone, if there are any, they are applied to the database",
        "tags": [
          "update"
        ],
        "operationId": "postUpdate",
        "responses": {
          "202": {
            "description": "Update started"
          },
          "401": {
            "description": "Unauthorized request"
          }
        }
      }
    }
  },
  "definitions": {
    "card": {
      "type": "object",
      "properties": {
        "artistName": {
          "type": "string"
        },
        "attack": {
          "type": "integer"
        },
        "cardSetId": {
          "type": "integer"
        },
        "cardTypeId": {
          "type": "integer"
        },
        "classId": {
          "type": "integer"
        },
        "collectible": {
          "type": "integer"
        },
        "duals": {
          "$ref": "#/definitions/duals"
        },
        "flavorText": {
          "type": "string"
        },
        "health": {
          "type": "integer"
        },
        "id": {
          "description": "This is the ID from Blizzard's API",
          "type": "integer"
        },
        "image": {
          "description": "Link to a PNG image of the card",
          "type": "string"
        },
        "imageGold": {
          "description": "Link to a PNG image of the golden version of the card",
          "type": "string"
        },
        "keywordIds": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "manaCost": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "parentId": {
          "type": "integer"
        },
        "rarityId": {
          "type": "integer"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "cards": {
      "type": "object",
      "properties": {
        "cardCount": {
          "type": "integer"
        },
        "cards": {
          "description": "if there are no cards, the array can be null",
          "type": "array",
          "items": {
            "$ref": "#/definitions/card"
          }
        },
        "page": {
          "type": "integer"
        },
        "pageCount": {
          "type": "integer"
        }
      }
    },
    "classes": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "duals": {
      "type": "object",
      "properties": {
        "constructed": {
          "type": "boolean"
        },
        "relevant": {
          "type": "boolean"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "description": "HTTP response code \u003e= 400",
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "info": {
      "type": "object",
      "properties": {
        "amountOfCards": {
          "type": "integer"
        },
        "lastUpdate": {
          "description": "formatted as RFC 3339",
          "type": "string",
          "format": "date-time"
        },
        "systemStartTime": {
          "description": "formatted as RFC 3339",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "keywords": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "rarities": {
      "type": "object",
      "properties": {
        "craftingcost": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "dustvalue": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "richCard": {
      "type": "object",
      "properties": {
        "artistName": {
          "type": "string"
        },
        "attack": {
          "type": "integer"
        },
        "cardSet": {
          "type": "string"
        },
        "cardType": {
          "type": "string"
        },
        "class": {
          "type": "string"
        },
        "collectible": {
          "type": "integer"
        },
        "duals": {
          "$ref": "#/definitions/duals"
        },
        "flavorText": {
          "type": "string"
        },
        "health": {
          "type": "integer"
        },
        "id": {
          "description": "This is the ID from Blizzard's API",
          "type": "integer"
        },
        "image": {
          "description": "Link to a PNG image of the card",
          "type": "string"
        },
        "imageGold": {
          "description": "Link to a PNG image of the golden version of the card",
          "type": "string"
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "manaCost": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "parentId": {
          "type": "integer"
        },
        "rarity": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "richCards": {
      "type": "object",
      "properties": {
        "cardCount": {
          "type": "integer"
        },
        "cards": {
          "description": "if there are no cards, the array can be null",
          "type": "array",
          "items": {
            "$ref": "#/definitions/richCard"
          }
        },
        "page": {
          "type": "integer"
        },
        "pageCount": {
          "type": "integer"
        }
      }
    },
    "sets": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "types": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "attackParam": {
      "type": "integer",
      "name": "attack",
      "in": "query"
    },
    "cardNameParam": {
      "minLength": 1,
      "type": "string",
      "name": "name",
      "in": "query"
    },
    "classParam": {
      "maximum": 14,
      "minimum": 1,
      "type": "integer",
      "name": "class",
      "in": "query"
    },
    "healthParam": {
      "type": "integer",
      "name": "health",
      "in": "query"
    },
    "keywordsParam": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "collectionFormat": "multi",
      "name": "keywords",
      "in": "query"
    },
    "limitParam": {
      "maximum": 100,
      "minimum": 1,
      "type": "integer",
      "default": 20,
      "name": "limit",
      "in": "query"
    },
    "manaCostParam": {
      "maximum": 99,
      "type": "integer",
      "name": "manaCost",
      "in": "query"
    },
    "pageParam": {
      "minimum": 1,
      "type": "integer",
      "default": 1,
      "name": "page",
      "in": "query"
    },
    "rarityParam": {
      "maximum": 5,
      "minimum": 1,
      "type": "integer",
      "name": "rarity",
      "in": "query"
    },
    "setParam": {
      "type": "integer",
      "name": "set",
      "in": "query"
    },
    "typeParam": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "collectionFormat": "multi",
      "name": "type",
      "in": "query"
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Serves Hearthstone cards",
    "title": "Hearthstone Card Service API",
    "contact": {
      "name": "William Winkler",
      "email": "williambwinkler@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/cards": {
      "get": {
        "description": "Returns cards as they are stored",
        "tags": [
          "cards"
        ],
        "operationId": "getCards",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "name": "name",
            "in": "query"
          },
          {
            "maximum": 99,
            "minimum": 0,
            "type": "integer",
            "name": "manaCost",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "integer",
            "name": "health",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "integer",
            "name": "attack",
            "in": "query"
          },
          {
            "maximum": 14,
            "minimum": 1,
            "type": "integer",
            "name": "class",
            "in": "query"
          },
          {
            "maximum": 5,
            "minimum": 1,
            "type": "integer",
            "name": "rarity",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "collectionFormat": "multi",
            "name": "type",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "collectionFormat": "multi",
            "name": "keywords",
            "in": "query"
          },
          {
            "type": "integer",
            "name": "set",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns cards by query. If there is no query, cards are returned by manaCost ascending.",
            "schema": {
              "$ref": "#/definitions/cards"
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/classes": {
      "get": {
        "description": "Serves card classes, e.g. Warlock or Neutral.",
        "tags": [
          "classes"
        ],
        "operationId": "getClasses",
        "responses": {
          "200": {
            "description": "Returns all classes",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/classes"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/keywords": {
      "get": {
        "description": "Serves card keywords, e.g. Taunt or Quest.",
        "tags": [
          "keywords"
        ],
        "operationId": "getKeywords",
        "responses": {
          "200": {
            "description": "Returns all keywords",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/keywords"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/rarities": {
      "get": {
        "description": "Serves card rarities, e.g. Common or Legendary.",
        "tags": [
          "rarities"
        ],
        "operationId": "getRarities",
        "responses": {
          "200": {
            "description": "Returns all rarities",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/rarities"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/richcards": {
      "get": {
        "description": "Rich cards contain names instead of IDs for e.g. CardType and CardSet.",
        "tags": [
          "cards"
        ],
        "operationId": "getRichCards",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "name": "name",
            "in": "query"
          },
          {
            "maximum": 99,
            "minimum": 0,
            "type": "integer",
            "name": "manaCost",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "integer",
            "name": "health",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "integer",
            "name": "attack",
            "in": "query"
          },
          {
            "maximum": 14,
            "minimum": 1,
            "type": "integer",
            "name": "class",
            "in": "query"
          },
          {
            "maximum": 5,
            "minimum": 1,
            "type": "integer",
            "name": "rarity",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "collectionFormat": "multi",
            "name": "type",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "collectionFormat": "multi",
            "name": "keywords",
            "in": "query"
          },
          {
            "type": "integer",
            "name": "set",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns rich cards by query. If there is no query, cards are returned by manaCost ascending.",
            "schema": {
              "$ref": "#/definitions/richCards"
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/sets": {
      "get": {
        "description": "Cards can belong to different sets or expansions. Returns all sets.",
        "tags": [
          "sets"
        ],
        "operationId": "getSets",
        "responses": {
          "200": {
            "description": "Returns all sets",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/sets"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/types": {
      "get": {
        "description": "Serves card types, e.g. Minion or Spell.",
        "tags": [
          "types"
        ],
        "operationId": "getTypes",
        "responses": {
          "200": {
            "description": "Returns all types",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/types"
              }
            }
          },
          "500": {
            "description": "Something went wrong internally",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/update": {
      "post": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Checks for updates to Hearthstone, if there are any, they are applied to the database",
        "tags": [
          "update"
        ],
        "operationId": "postUpdate",
        "responses": {
          "202": {
            "description": "Update started"
          },
          "401": {
            "description": "Unauthorized request"
          }
        }
      }
    }
  },
  "definitions": {
    "card": {
      "type": "object",
      "properties": {
        "artistName": {
          "type": "string"
        },
        "attack": {
          "type": "integer"
        },
        "cardSetId": {
          "type": "integer"
        },
        "cardTypeId": {
          "type": "integer"
        },
        "classId": {
          "type": "integer"
        },
        "collectible": {
          "type": "integer"
        },
        "duals": {
          "$ref": "#/definitions/duals"
        },
        "flavorText": {
          "type": "string"
        },
        "health": {
          "type": "integer"
        },
        "id": {
          "description": "This is the ID from Blizzard's API",
          "type": "integer"
        },
        "image": {
          "description": "Link to a PNG image of the card",
          "type": "string"
        },
        "imageGold": {
          "description": "Link to a PNG image of the golden version of the card",
          "type": "string"
        },
        "keywordIds": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "manaCost": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "parentId": {
          "type": "integer"
        },
        "rarityId": {
          "type": "integer"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "cards": {
      "type": "object",
      "properties": {
        "cardCount": {
          "type": "integer"
        },
        "cards": {
          "description": "if there are no cards, the array can be null",
          "type": "array",
          "items": {
            "$ref": "#/definitions/card"
          }
        },
        "page": {
          "type": "integer"
        },
        "pageCount": {
          "type": "integer"
        }
      }
    },
    "classes": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "duals": {
      "type": "object",
      "properties": {
        "constructed": {
          "type": "boolean"
        },
        "relevant": {
          "type": "boolean"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "description": "HTTP response code \u003e= 400",
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "info": {
      "type": "object",
      "properties": {
        "amountOfCards": {
          "type": "integer"
        },
        "lastUpdate": {
          "description": "formatted as RFC 3339",
          "type": "string",
          "format": "date-time"
        },
        "systemStartTime": {
          "description": "formatted as RFC 3339",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "keywords": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "rarities": {
      "type": "object",
      "properties": {
        "craftingcost": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "dustvalue": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "richCard": {
      "type": "object",
      "properties": {
        "artistName": {
          "type": "string"
        },
        "attack": {
          "type": "integer"
        },
        "cardSet": {
          "type": "string"
        },
        "cardType": {
          "type": "string"
        },
        "class": {
          "type": "string"
        },
        "collectible": {
          "type": "integer"
        },
        "duals": {
          "$ref": "#/definitions/duals"
        },
        "flavorText": {
          "type": "string"
        },
        "health": {
          "type": "integer"
        },
        "id": {
          "description": "This is the ID from Blizzard's API",
          "type": "integer"
        },
        "image": {
          "description": "Link to a PNG image of the card",
          "type": "string"
        },
        "imageGold": {
          "description": "Link to a PNG image of the golden version of the card",
          "type": "string"
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "manaCost": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "parentId": {
          "type": "integer"
        },
        "rarity": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    },
    "richCards": {
      "type": "object",
      "properties": {
        "cardCount": {
          "type": "integer"
        },
        "cards": {
          "description": "if there are no cards, the array can be null",
          "type": "array",
          "items": {
            "$ref": "#/definitions/richCard"
          }
        },
        "page": {
          "type": "integer"
        },
        "pageCount": {
          "type": "integer"
        }
      }
    },
    "sets": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "types": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "attackParam": {
      "minimum": 0,
      "type": "integer",
      "name": "attack",
      "in": "query"
    },
    "cardNameParam": {
      "minLength": 1,
      "type": "string",
      "name": "name",
      "in": "query"
    },
    "classParam": {
      "maximum": 14,
      "minimum": 1,
      "type": "integer",
      "name": "class",
      "in": "query"
    },
    "healthParam": {
      "minimum": 0,
      "type": "integer",
      "name": "health",
      "in": "query"
    },
    "keywordsParam": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "collectionFormat": "multi",
      "name": "keywords",
      "in": "query"
    },
    "limitParam": {
      "maximum": 100,
      "minimum": 1,
      "type": "integer",
      "default": 20,
      "name": "limit",
      "in": "query"
    },
    "manaCostParam": {
      "maximum": 99,
      "minimum": 0,
      "type": "integer",
      "name": "manaCost",
      "in": "query"
    },
    "pageParam": {
      "minimum": 1,
      "type": "integer",
      "default": 1,
      "name": "page",
      "in": "query"
    },
    "rarityParam": {
      "maximum": 5,
      "minimum": 1,
      "type": "integer",
      "name": "rarity",
      "in": "query"
    },
    "setParam": {
      "type": "integer",
      "name": "set",
      "in": "query"
    },
    "typeParam": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "collectionFormat": "multi",
      "name": "type",
      "in": "query"
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  }
}`))
}
