// Code generated by go-swagger; DO NOT EDIT.

package sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1SetsHandlerFunc turns a function with the right signature into a get v1 sets handler
type GetV1SetsHandlerFunc func(GetV1SetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1SetsHandlerFunc) Handle(params GetV1SetsParams) middleware.Responder {
	return fn(params)
}

// GetV1SetsHandler interface for that can handle valid get v1 sets params
type GetV1SetsHandler interface {
	Handle(GetV1SetsParams) middleware.Responder
}

// NewGetV1Sets creates a new http.Handler for the get v1 sets operation
func NewGetV1Sets(ctx *middleware.Context, handler GetV1SetsHandler) *GetV1Sets {
	return &GetV1Sets{Context: ctx, Handler: handler}
}

/*
	GetV1Sets swagger:route GET /v1/sets sets getV1Sets

Cards can belong to different sets or expansions. This serves all sets and their info.
*/
type GetV1Sets struct {
	Context *middleware.Context
	Handler GetV1SetsHandler
}

func (o *GetV1Sets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetV1SetsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
