// Code generated by go-swagger; DO NOT EDIT.

package sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetV1SetsOKCode is the HTTP code returned for type GetV1SetsOK
const GetV1SetsOKCode int = 200

/*
GetV1SetsOK Returns all sets

swagger:response getV1SetsOK
*/
type GetV1SetsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Sets `json:"body,omitempty"`
}

// NewGetV1SetsOK creates GetV1SetsOK with default headers values
func NewGetV1SetsOK() *GetV1SetsOK {

	return &GetV1SetsOK{}
}

// WithPayload adds the payload to the get v1 sets o k response
func (o *GetV1SetsOK) WithPayload(payload []*models.Sets) *GetV1SetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 sets o k response
func (o *GetV1SetsOK) SetPayload(payload []*models.Sets) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1SetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Sets, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1SetsInternalServerErrorCode is the HTTP code returned for type GetV1SetsInternalServerError
const GetV1SetsInternalServerErrorCode int = 500

/*
GetV1SetsInternalServerError Something went wrong internally

swagger:response getV1SetsInternalServerError
*/
type GetV1SetsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1SetsInternalServerError creates GetV1SetsInternalServerError with default headers values
func NewGetV1SetsInternalServerError() *GetV1SetsInternalServerError {

	return &GetV1SetsInternalServerError{}
}

// WithPayload adds the payload to the get v1 sets internal server error response
func (o *GetV1SetsInternalServerError) WithPayload(payload *models.Error) *GetV1SetsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 sets internal server error response
func (o *GetV1SetsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1SetsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
