// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/cards"
	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/classes"
	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/keywords"
	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/rarities"
	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/sets"
	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/types"
	"github.com/williamwinkler/hs-card-service/codegen/restapi/operations/update"
)

// NewHearthstoneCardServiceAPI creates a new HearthstoneCardService instance
func NewHearthstoneCardServiceAPI(spec *loads.Document) *HearthstoneCardServiceAPI {
	return &HearthstoneCardServiceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		CardsGetV1CardsHandler: cards.GetV1CardsHandlerFunc(func(params cards.GetV1CardsParams) middleware.Responder {
			return middleware.NotImplemented("operation cards.GetV1Cards has not yet been implemented")
		}),
		ClassesGetV1ClassesHandler: classes.GetV1ClassesHandlerFunc(func(params classes.GetV1ClassesParams) middleware.Responder {
			return middleware.NotImplemented("operation classes.GetV1Classes has not yet been implemented")
		}),
		KeywordsGetV1KeywordsHandler: keywords.GetV1KeywordsHandlerFunc(func(params keywords.GetV1KeywordsParams) middleware.Responder {
			return middleware.NotImplemented("operation keywords.GetV1Keywords has not yet been implemented")
		}),
		RaritiesGetV1RaritiesHandler: rarities.GetV1RaritiesHandlerFunc(func(params rarities.GetV1RaritiesParams) middleware.Responder {
			return middleware.NotImplemented("operation rarities.GetV1Rarities has not yet been implemented")
		}),
		CardsGetV1RichcardsHandler: cards.GetV1RichcardsHandlerFunc(func(params cards.GetV1RichcardsParams) middleware.Responder {
			return middleware.NotImplemented("operation cards.GetV1Richcards has not yet been implemented")
		}),
		SetsGetV1SetsHandler: sets.GetV1SetsHandlerFunc(func(params sets.GetV1SetsParams) middleware.Responder {
			return middleware.NotImplemented("operation sets.GetV1Sets has not yet been implemented")
		}),
		TypesGetV1TypesHandler: types.GetV1TypesHandlerFunc(func(params types.GetV1TypesParams) middleware.Responder {
			return middleware.NotImplemented("operation types.GetV1Types has not yet been implemented")
		}),
		UpdatePostUpdateHandler: update.PostUpdateHandlerFunc(func(params update.PostUpdateParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation update.PostUpdate has not yet been implemented")
		}),

		// Applies when the Authorization header is set with the Basic scheme
		BasicAuthAuth: func(user string, pass string) (interface{}, error) {
			return nil, errors.NotImplemented("basic auth  (basicAuth) has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*HearthstoneCardServiceAPI Serves Hearthstone cards */
type HearthstoneCardServiceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BasicAuthAuth registers a function that takes username and password and returns a principal
	// it performs authentication with basic auth
	BasicAuthAuth func(string, string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// CardsGetV1CardsHandler sets the operation handler for the get v1 cards operation
	CardsGetV1CardsHandler cards.GetV1CardsHandler
	// ClassesGetV1ClassesHandler sets the operation handler for the get v1 classes operation
	ClassesGetV1ClassesHandler classes.GetV1ClassesHandler
	// KeywordsGetV1KeywordsHandler sets the operation handler for the get v1 keywords operation
	KeywordsGetV1KeywordsHandler keywords.GetV1KeywordsHandler
	// RaritiesGetV1RaritiesHandler sets the operation handler for the get v1 rarities operation
	RaritiesGetV1RaritiesHandler rarities.GetV1RaritiesHandler
	// CardsGetV1RichcardsHandler sets the operation handler for the get v1 richcards operation
	CardsGetV1RichcardsHandler cards.GetV1RichcardsHandler
	// SetsGetV1SetsHandler sets the operation handler for the get v1 sets operation
	SetsGetV1SetsHandler sets.GetV1SetsHandler
	// TypesGetV1TypesHandler sets the operation handler for the get v1 types operation
	TypesGetV1TypesHandler types.GetV1TypesHandler
	// UpdatePostUpdateHandler sets the operation handler for the post update operation
	UpdatePostUpdateHandler update.PostUpdateHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *HearthstoneCardServiceAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *HearthstoneCardServiceAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *HearthstoneCardServiceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *HearthstoneCardServiceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *HearthstoneCardServiceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *HearthstoneCardServiceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *HearthstoneCardServiceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *HearthstoneCardServiceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *HearthstoneCardServiceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the HearthstoneCardServiceAPI
func (o *HearthstoneCardServiceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BasicAuthAuth == nil {
		unregistered = append(unregistered, "BasicAuthAuth")
	}

	if o.CardsGetV1CardsHandler == nil {
		unregistered = append(unregistered, "cards.GetV1CardsHandler")
	}
	if o.ClassesGetV1ClassesHandler == nil {
		unregistered = append(unregistered, "classes.GetV1ClassesHandler")
	}
	if o.KeywordsGetV1KeywordsHandler == nil {
		unregistered = append(unregistered, "keywords.GetV1KeywordsHandler")
	}
	if o.RaritiesGetV1RaritiesHandler == nil {
		unregistered = append(unregistered, "rarities.GetV1RaritiesHandler")
	}
	if o.CardsGetV1RichcardsHandler == nil {
		unregistered = append(unregistered, "cards.GetV1RichcardsHandler")
	}
	if o.SetsGetV1SetsHandler == nil {
		unregistered = append(unregistered, "sets.GetV1SetsHandler")
	}
	if o.TypesGetV1TypesHandler == nil {
		unregistered = append(unregistered, "types.GetV1TypesHandler")
	}
	if o.UpdatePostUpdateHandler == nil {
		unregistered = append(unregistered, "update.PostUpdateHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *HearthstoneCardServiceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *HearthstoneCardServiceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "basicAuth":
			result[name] = o.BasicAuthenticator(o.BasicAuthAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *HearthstoneCardServiceAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *HearthstoneCardServiceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *HearthstoneCardServiceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *HearthstoneCardServiceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the hearthstone card service API
func (o *HearthstoneCardServiceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *HearthstoneCardServiceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/cards"] = cards.NewGetV1Cards(o.context, o.CardsGetV1CardsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/classes"] = classes.NewGetV1Classes(o.context, o.ClassesGetV1ClassesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/keywords"] = keywords.NewGetV1Keywords(o.context, o.KeywordsGetV1KeywordsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/rarities"] = rarities.NewGetV1Rarities(o.context, o.RaritiesGetV1RaritiesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/richcards"] = cards.NewGetV1Richcards(o.context, o.CardsGetV1RichcardsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/sets"] = sets.NewGetV1Sets(o.context, o.SetsGetV1SetsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/types"] = types.NewGetV1Types(o.context, o.TypesGetV1TypesHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/update"] = update.NewPostUpdate(o.context, o.UpdatePostUpdateHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *HearthstoneCardServiceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *HearthstoneCardServiceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *HearthstoneCardServiceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *HearthstoneCardServiceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *HearthstoneCardServiceAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
