// Code generated by go-swagger; DO NOT EDIT.

package keywords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetKeywordsHandlerFunc turns a function with the right signature into a get keywords handler
type GetKeywordsHandlerFunc func(GetKeywordsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKeywordsHandlerFunc) Handle(params GetKeywordsParams) middleware.Responder {
	return fn(params)
}

// GetKeywordsHandler interface for that can handle valid get keywords params
type GetKeywordsHandler interface {
	Handle(GetKeywordsParams) middleware.Responder
}

// NewGetKeywords creates a new http.Handler for the get keywords operation
func NewGetKeywords(ctx *middleware.Context, handler GetKeywordsHandler) *GetKeywords {
	return &GetKeywords{Context: ctx, Handler: handler}
}

/*
	GetKeywords swagger:route GET /keywords keywords getKeywords

Serves the different keywords cards can have. Fx "Taunt" or "Quest"
*/
type GetKeywords struct {
	Context *middleware.Context
	Handler GetKeywordsHandler
}

func (o *GetKeywords) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetKeywordsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
