// Code generated by go-swagger; DO NOT EDIT.

package keywords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetKeywordsOKCode is the HTTP code returned for type GetKeywordsOK
const GetKeywordsOKCode int = 200

/*
GetKeywordsOK Returns all keywords

swagger:response getKeywordsOK
*/
type GetKeywordsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Keywords `json:"body,omitempty"`
}

// NewGetKeywordsOK creates GetKeywordsOK with default headers values
func NewGetKeywordsOK() *GetKeywordsOK {

	return &GetKeywordsOK{}
}

// WithPayload adds the payload to the get keywords o k response
func (o *GetKeywordsOK) WithPayload(payload []*models.Keywords) *GetKeywordsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get keywords o k response
func (o *GetKeywordsOK) SetPayload(payload []*models.Keywords) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKeywordsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Keywords, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetKeywordsInternalServerErrorCode is the HTTP code returned for type GetKeywordsInternalServerError
const GetKeywordsInternalServerErrorCode int = 500

/*
GetKeywordsInternalServerError Something went wrong internally

swagger:response getKeywordsInternalServerError
*/
type GetKeywordsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetKeywordsInternalServerError creates GetKeywordsInternalServerError with default headers values
func NewGetKeywordsInternalServerError() *GetKeywordsInternalServerError {

	return &GetKeywordsInternalServerError{}
}

// WithPayload adds the payload to the get keywords internal server error response
func (o *GetKeywordsInternalServerError) WithPayload(payload *models.Error) *GetKeywordsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get keywords internal server error response
func (o *GetKeywordsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKeywordsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
