// Code generated by go-swagger; DO NOT EDIT.

package keywords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1KeywordsHandlerFunc turns a function with the right signature into a get v1 keywords handler
type GetV1KeywordsHandlerFunc func(GetV1KeywordsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1KeywordsHandlerFunc) Handle(params GetV1KeywordsParams) middleware.Responder {
	return fn(params)
}

// GetV1KeywordsHandler interface for that can handle valid get v1 keywords params
type GetV1KeywordsHandler interface {
	Handle(GetV1KeywordsParams) middleware.Responder
}

// NewGetV1Keywords creates a new http.Handler for the get v1 keywords operation
func NewGetV1Keywords(ctx *middleware.Context, handler GetV1KeywordsHandler) *GetV1Keywords {
	return &GetV1Keywords{Context: ctx, Handler: handler}
}

/*
	GetV1Keywords swagger:route GET /v1/keywords keywords getV1Keywords

Serves the different keywords cards can have. Fx "Taunt" or "Quest"
*/
type GetV1Keywords struct {
	Context *middleware.Context
	Handler GetV1KeywordsHandler
}

func (o *GetV1Keywords) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetV1KeywordsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
