// Code generated by go-swagger; DO NOT EDIT.

package rarities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetRaritiesOKCode is the HTTP code returned for type GetRaritiesOK
const GetRaritiesOKCode int = 200

/*
GetRaritiesOK Returns all rarities

swagger:response getRaritiesOK
*/
type GetRaritiesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Rarities `json:"body,omitempty"`
}

// NewGetRaritiesOK creates GetRaritiesOK with default headers values
func NewGetRaritiesOK() *GetRaritiesOK {

	return &GetRaritiesOK{}
}

// WithPayload adds the payload to the get rarities o k response
func (o *GetRaritiesOK) WithPayload(payload []*models.Rarities) *GetRaritiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rarities o k response
func (o *GetRaritiesOK) SetPayload(payload []*models.Rarities) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRaritiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Rarities, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRaritiesInternalServerErrorCode is the HTTP code returned for type GetRaritiesInternalServerError
const GetRaritiesInternalServerErrorCode int = 500

/*
GetRaritiesInternalServerError Something went wrong internally

swagger:response getRaritiesInternalServerError
*/
type GetRaritiesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRaritiesInternalServerError creates GetRaritiesInternalServerError with default headers values
func NewGetRaritiesInternalServerError() *GetRaritiesInternalServerError {

	return &GetRaritiesInternalServerError{}
}

// WithPayload adds the payload to the get rarities internal server error response
func (o *GetRaritiesInternalServerError) WithPayload(payload *models.Error) *GetRaritiesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rarities internal server error response
func (o *GetRaritiesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRaritiesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
