// Code generated by go-swagger; DO NOT EDIT.

package rarities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/williamwinkler/hs-card-service/codegen/models"
)

// GetV1RaritiesOKCode is the HTTP code returned for type GetV1RaritiesOK
const GetV1RaritiesOKCode int = 200

/*
GetV1RaritiesOK Returns all rarities

swagger:response getV1RaritiesOK
*/
type GetV1RaritiesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Rarities `json:"body,omitempty"`
}

// NewGetV1RaritiesOK creates GetV1RaritiesOK with default headers values
func NewGetV1RaritiesOK() *GetV1RaritiesOK {

	return &GetV1RaritiesOK{}
}

// WithPayload adds the payload to the get v1 rarities o k response
func (o *GetV1RaritiesOK) WithPayload(payload []*models.Rarities) *GetV1RaritiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 rarities o k response
func (o *GetV1RaritiesOK) SetPayload(payload []*models.Rarities) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1RaritiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Rarities, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1RaritiesInternalServerErrorCode is the HTTP code returned for type GetV1RaritiesInternalServerError
const GetV1RaritiesInternalServerErrorCode int = 500

/*
GetV1RaritiesInternalServerError Something went wrong internally

swagger:response getV1RaritiesInternalServerError
*/
type GetV1RaritiesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetV1RaritiesInternalServerError creates GetV1RaritiesInternalServerError with default headers values
func NewGetV1RaritiesInternalServerError() *GetV1RaritiesInternalServerError {

	return &GetV1RaritiesInternalServerError{}
}

// WithPayload adds the payload to the get v1 rarities internal server error response
func (o *GetV1RaritiesInternalServerError) WithPayload(payload *models.Error) *GetV1RaritiesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 rarities internal server error response
func (o *GetV1RaritiesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1RaritiesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
